services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - bankingNetwork
  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - bankingNetwork    
  mysql:
    image: mysql:8.0.4
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'vaxidrez'
      MYSQL_PASSWORD: 'VaxiDrez2005$$'
      MYSQL_ROOT_PASSWORD: 'VaxiDrez2005$$'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bankingNetwork 
  mongodb:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "vaxidrez"
      MONGO_INITDB_ROOT_PASSWORD: "VaxiDrez2005$$"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - bankingNetwork
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false 
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - bankingNetwork
  my_service:
    build:
      context: .
    image: n5now:latest
    restart: always
    ports:
      - "82:82"
    environment:
      - DB_SERVER=172.20.0.1  # Cambiar a 'sqlserver' si estás usando SQL Server
      - DB_DATABASE=bdtestn5
      - DB_USER=sa
      - DB_PASSWORD=tribunal
      - CONNECTION_STRING=data source=host.docker.internal,1433;initial catalog=n5nowtest;User Id=sa;Password=tribunal;integrated security=false;Trust Server Certificate=true
    networks:
      - bankingNetwork        
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local    
  esdata:
    driver: local  
networks:
  bankingNetwork:
    driver: bridge